# Generated by Django 3.1.1 on 2020-09-28 18:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDoc', models.TextField()),
                ('hasFullDate', models.TextField(blank=True, default=None, null=True)),
                ('hasPubYear', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('publishedYear', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('fileLocation', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/storage'), upload_to='')),
                ('typeDoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='archive.documenttype', verbose_name='DocType')),
            ],
        ),
    ]
