# Generated by Django 3.1.2 on 2021-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedocument",
            name="date",
        ),
        migrations.RemoveField(
            model_name="archivedocument",
            name="description",
        ),
        migrations.AlterField(
            model_name="archivedocument",
            name="file_location",
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name="archivedocument",
            name="type_doc",
            field=models.CharField(
                choices=[
                    ("Budsjett og Regnskap", "Budsjett og Regnskap"),
                    ("Generalforsamling", "Generalforsamling"),
                    ("Årbøker", "Årbøker"),
                    ("Foreningens lover", "Foreningens lover"),
                    ("Støtte fra HS", "Støtte fra HS"),
                    ("Utveksling", "Utveksling"),
                    ("Annet", "Annet"),
                ],
                max_length=20,
            ),
        ),
    ]
