# Generated by Django 3.1.1 on 2020-09-28 18:57

import apps.archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20200928_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='typeDoc',
            field=models.CharField(choices=[(apps.archive.models.FileType['BUD'], 'Budget'), (apps.archive.models.FileType['ACC'], 'Accounting'), (apps.archive.models.FileType['SUM'], 'Summary'), (apps.archive.models.FileType['YBO'], 'Yearbook'), (apps.archive.models.FileType['GLI'], 'Guidelines'), (apps.archive.models.FileType['REG'], 'Regulation'), (apps.archive.models.FileType['STA'], 'Statues'), (apps.archive.models.FileType['OTH'], 'Others')], max_length=12),
        ),
    ]
