# Generated by Django 3.1.1 on 2020-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20200928_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='typeDoc',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Accounting', 'Accounting'), ('Summary', 'Summary'), ('Yearbook', 'Yearbook'), ('Guidelines', 'Guidelines'), ('Regulation', 'Regulation'), ('Statues', 'Statues'), ('Others', 'Others')], max_length=12),
        ),
    ]
