# Generated by Django 3.1.2 on 2021-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20210204_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
