# Generated by Django 3.1.2 on 2021-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_auto_20210204_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedocument",
            name="year",
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
    ]
