# Generated by Django 3.1.1 on 2020-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20200928_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedocument',
            name='publishedYear',
        ),
        migrations.AlterField(
            model_name='archivedocument',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
