# Generated by Django 3.1.1 on 2020-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20201001_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='fileLocation',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
