# Generated by Django 3.1.1 on 2020-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_auto_20201007_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='fileLocation',
            field=models.TextField(default=None),
        ),
    ]
