# Generated by Django 3.1.2 on 2021-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20210209_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedocument',
            name='year',
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='web_link',
            field=models.CharField(default=None, max_length=2050, null=True),
        ),
    ]
