# Generated by Django 3.1.2 on 2021-02-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20210225_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedocument',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
