# Generated by Django 3.1.2 on 2021-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_archivedocument_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedocument',
            name='web_link',
            field=models.CharField(blank=True, default=None, max_length=2050, null=True),
        ),
    ]
