# Generated by Django 3.2.16 on 2023-01-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0015_alter_archivedocument_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedocument",
            name="type_doc",
            field=models.CharField(
                choices=[
                    ("Budsjett og Regnskap", "Budsjett og Regnskap"),
                    ("Generalforsamling", "Generalforsamling"),
                    ("Årbøker", "Årbøker"),
                    ("Foreningens lover", "Foreningens lover"),
                    ("Støtte fra HS", "Støtte fra HS"),
                    ("Utveksling", "Utveksling"),
                    ("Annet", "Annet"),
                    ("Januscript", "Januscript"),
                ],
                max_length=20,
            ),
        ),
    ]
