# Generated by Django 3.2.18 on 2023-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0016_alter_archivedocument_type_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedocument",
            name="thumbnail",
            field=models.URLField(null=True),
        ),
    ]
