# Generated by Django 3.2.18 on 2023-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0018_auto_20230320_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedocument",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
