# Generated by ChatGPT

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cabins", "0029_auto_20240226_1815"),
        ("users", "0020_auto_20220128_1632"),
    ]

    operations = [
        migrations.CreateModel(
            name="NfcCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid_hex", models.CharField(db_index=True, max_length=14, unique=True)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [("manage_nfc", "Can manage NFC cards, assignments, and access grants")],
            },
        ),
        migrations.CreateModel(
            name="NfcCardAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_holder_name", models.CharField(blank=True, default="", max_length=150)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("access_start", models.DateTimeField(blank=True, null=True)),
                ("access_end", models.DateTimeField(blank=True, null=True)),
                ("permanent_access", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, default="", max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_card_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="nfc.nfccard",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_card_assignments_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_card_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "revoked_at"], name="nfc_nfc_card_user_id_8c98dc_idx"),
                    models.Index(fields=["card", "revoked_at"], name="nfc_nfc_card_card_id_e57ac2_idx"),
                    models.Index(fields=["access_start", "access_end"], name="nfc_nfc_car_access__4e2f09_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("card",),
                        name="unique_active_nfc_assignment_per_card",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True), ("user__isnull", False)),
                        fields=("user",),
                        name="unique_active_nfc_assignment_per_user",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("access_end__isnull", True), ("access_start__isnull", True), _connector="OR")
                        | models.Q(("access_end__gte", models.F("access_start"))),
                        name="nfc_assignment_access_end_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NfcAccessGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("BOOKING", "Booking")],
                        default="MANUAL",
                        max_length=25,
                    ),
                ),
                (
                    "participant_policy",
                    models.CharField(
                        choices=[("BOOKER_ONLY", "Booker only"), ("ALL_PARTICIPANTS", "All participants")],
                        default="BOOKER_ONLY",
                        max_length=25,
                    ),
                ),
                ("access_start", models.DateTimeField(blank=True, null=True)),
                ("access_end", models.DateTimeField(blank=True, null=True)),
                ("permanent_access", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_access_grants",
                        to="cabins.booking",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_access_grants_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_to_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_grants",
                        to="nfc.nfccard",
                    ),
                ),
                (
                    "granted_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_access_grants_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scope", "booking"], name="nfc_nfc_acc_scope_b_06bf8c_idx"),
                    models.Index(fields=["granted_to_user", "revoked_at"], name="nfc_nfc_acc_granted_0ba9ef_idx"),
                    models.Index(fields=["granted_to_card", "revoked_at"], name="nfc_nfc_acc_granted_b8d108_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(("access_end__isnull", True), ("access_start__isnull", True), _connector="OR")
                        | models.Q(("access_end__gte", models.F("access_start"))),
                        name="nfc_grant_access_end_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NfcAccessEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ACCESS_GRANTED", "Access granted"),
                            ("ACCESS_DENIED", "Access denied"),
                            ("DOOR_OPENED", "Door opened"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NFC_READER", "NFC reader"),
                            ("MANUAL_KEY", "Manual key"),
                            ("BACKEND", "Backend"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("door_identifier", models.CharField(blank=True, default="", max_length=120)),
                ("uid_hex_reported", models.CharField(blank=True, default="", max_length=14)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="nfc.nfccard",
                    ),
                ),
                (
                    "card_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="nfc.nfccardassignment",
                    ),
                ),
                (
                    "resolved_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfc_access_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["occurred_at"], name="nfc_nfc_acc_occurre_65ac6b_idx"),
                    models.Index(fields=["door_identifier", "occurred_at"], name="nfc_nfc_acc_door_id_9f0803_idx"),
                    models.Index(fields=["uid_hex_reported", "occurred_at"], name="nfc_nfc_acc_uid_hex_6ce890_idx"),
                ],
            },
        ),
    ]
