# Generated by Django 3.2.25 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfc", "0003_nfccardassignment_pin_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="NfcSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_user_uid_self_service",
                    models.BooleanField(default=True),
                ),
                (
                    "allow_7_byte_uid",
                    models.BooleanField(default=True),
                ),
                (
                    "allow_4_byte_uid",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "NFC settings",
                "verbose_name_plural": "NFC settings",
            },
        ),
    ]
