# Generated by Django 3.2.25 on 2026-08-11

import re

from django.db import migrations, models


def _to_csn(value: str, allow_blank: bool = False) -> str:
    raw = (value or "").strip()
    if allow_blank and raw == "":
        return ""

    digits_only = re.sub(r"\D", "", raw)
    if len(digits_only) == 10:
        return digits_only

    compact_hex = re.sub(r"[^0-9A-Fa-f]", "", raw)
    if len(compact_hex) in (8, 14) and re.fullmatch(r"[0-9A-Fa-f]+", compact_hex):
        csn_value = int.from_bytes(bytes.fromhex(compact_hex[:8]), byteorder="little")
        return f"{csn_value:010d}"

    raise ValueError(f"Could not convert UID value '{raw}' to 10-digit CSN")


def convert_uid_values_to_csn(apps, schema_editor):
    nfc_card_model = apps.get_model("nfc", "NfcCard")
    nfc_access_event_model = apps.get_model("nfc", "NfcAccessEvent")

    # Pre-production data reset: existing cards can collapse to identical CSN values
    # during conversion, which violates the unique constraint on uid_hex.
    # The project has explicitly accepted purging NFC cards at this stage.
    nfc_card_model.objects.all().delete()

    for event in nfc_access_event_model.objects.all().iterator():
        converted = _to_csn(event.uid_hex_reported, allow_blank=True)
        if converted != event.uid_hex_reported:
            event.uid_hex_reported = converted
            event.save(update_fields=["uid_hex_reported"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("nfc", "0004_nfcsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nfcsettings",
            name="allow_4_byte_uid",
        ),
        migrations.RemoveField(
            model_name="nfcsettings",
            name="allow_7_byte_uid",
        ),
        migrations.RunPython(convert_uid_values_to_csn, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="nfcaccessevent",
            name="uid_hex_reported",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="nfccard",
            name="uid_hex",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
