# Generated by Django 3.2.25 on 2026-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0005_uid_to_10_digit_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nfcaccessevent',
            name='nfc_nfcacce_uid_hex_66e904_idx',
        ),
        migrations.RenameField(
            model_name='nfcaccessevent',
            old_name='uid_hex_reported',
            new_name='mifare_csn_reported',
        ),
        migrations.RenameField(
            model_name='nfccard',
            old_name='uid_hex',
            new_name='mifare_csn',
        ),
        migrations.RenameField(
            model_name='nfcsettings',
            old_name='allow_user_uid_self_service',
            new_name='allow_user_mifare_csn_self_service',
        ),
        migrations.AddIndex(
            model_name='nfcaccessevent',
            index=models.Index(fields=['mifare_csn_reported', 'occurred_at'], name='nfc_nfcacce_mifare__326846_idx'),
        ),
    ]
