export const DEFAULTINPUT: Record<string, any> = {
  title: "",
  description: "",
  startTime: "",
  endTime: "",
  location: "",
  organizationId: "",
  categoryId: "",
  image: "",
  deadline: "",
  signupOpenDate: "",
  availableSlots: "",
  // price: undefined,
  shortDescription: "",
  hasExtraInformation: false,
  contactEmail: "",
  bindingSignup: false,
  allowedGradeYears: [1, 2, 3, 4, 5],
};
