# Generated by Django 3.1.1 on 2020-10-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20201012_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.questiontype'),
        ),
    ]
