# Generated by Django 3.1.1 on 2020-10-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20201012_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ManyToManyField(related_name='surveys', through='surveys.SurveyQuestion', to='surveys.Question'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='offered_answer',
            field=models.ManyToManyField(related_name='surveyquestions', to='surveys.OfferedAnswer'),
        ),
    ]
