# Generated by Django 3.1.1 on 2020-10-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20201012_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion'),
        ),
    ]
