# Generated by Django 3.1.1 on 2020-10-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201012_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='survey_question',
        ),
    ]
