# Generated by Django 3.1.2 on 2020-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20201012_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='position',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
