# Generated by Django 3.1.1 on 2020-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20201026_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='descriptive_name',
            new_name='name',
        ),
    ]
