# Generated by Django 3.1.2 on 2020-10-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20201026_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='offered_answer',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='offered_answers',
            field=models.ManyToManyField(to='surveys.OfferedAnswer'),
        ),
    ]
