# Generated by Django 3.1.1 on 2020-10-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20201026_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
