# Generated by Django 3.1.1 on 2020-10-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20201029_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
