# Generated by Django 3.1.1 on 2020-10-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyQuestion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='survey_question',
            new_name='question',
        ),
    ]
