# Generated by Django 3.1.2 on 2021-02-25 15:50

from django.db import migrations

def remove_duplicate_answers(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    
    unique_answers = []
    for answer in Answer.objects.all():
        info_tuple = (answer.question.id, answer.user.id)
        if info_tuple in unique_answers:
            answer.delete()
        else:
            unique_answers.append(info_tuple)




class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_auto_20201029_1817'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_answers),
    ]
