# Generated by Django 3.1.2 on 2021-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20210225_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
