# Generated by Django 3.1.2 on 2021-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_question_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('position', 'survey'), name='unique question position per survey'),
        ),
    ]
