# Generated by Django 3.1.2 on 2021-03-01 17:59

from django.db import migrations

def non_destructively_fill_empty_answers(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")

    updated_answers = Answer.objects.filter(answer="")
    for answer in updated_answers:
        answer.answer = "N/A"

    Answer.objects.bulk_update(updated_answers, fields=["answer"])


def non_destructively_empty_answers(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")

    updated_answers = Answer.objects.filter(answer="N/A")
    for answer in updated_answers:
        answer.answer = ""

    Answer.objects.bulk_update(updated_answers, fields=["answer"])



class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20210301_1857'),
    ]

    operations = [
        migrations.RunPython(non_destructively_fill_empty_answers, non_destructively_empty_answers)
    ]
