# Generated by Django 3.1.2 on 2021-03-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20210301_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferedAnswer',
            new_name='Option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='offered_answers',
        ),
    ]
