# Generated by Django 3.1.2 on 2021-03-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20210311_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question'),
            preserve_default=False,
        ),
    ]
