# Generated by Django 3.1.2 on 2021-03-15 08:23

from django.db import migrations

def populate_question_types(apps, schema_editor):
    """Populate required question types to ensure a match with the frontend requirements."""

    QuestionType = apps.get_model("surveys", "QuestionType")
    types = ["Short answer", "Paragraph", "Multiple choice", "Drop-down"]

    QuestionType.bulk_create(
        QuestionType(name=type) for type in types
    )

class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_option_question'),
    ]

    operations = [
    ]
