# Generated by Django 3.1.2 on 2021-03-16 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid

def populate_uuid(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    for answer in Answer.objects.all():
        answer.uuid = uuid.uuid4()
        answer.save()

def reverse_population(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    for answer in Answer.objects.all():
        answer.uuid = None
        answer.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0024_populate_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(None, 'Unknown'), (0, 'Red'), (1, 'Yellow'), (2, 'Green')])),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2048)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='surveys.response')),
            ],
        ),
        migrations.RunPython(populate_uuid, reverse_population)
    ]
