# Generated by Django 3.1.2 on 2021-03-16 16:09

from typing import get_origin
from django.db import migrations, models
import django.db.models.deletion
from django.db.models.fields import NullBooleanField

def populate_response_field(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    Response = apps.get_model("surveys", "Response")

    for answer in Answer.objects.all():
        respondent = answer.user
        survey = answer.question.survey
        response, _ = Response.objects.get_or_create(respondent=respondent, survey=survey)
        answer.response = response
        answer.save()

def reverse_population(apps, schema_editor):
    Answer = apps.get_model("surveys", "Answer")
    Response = apps.get_model("surveys", "Response")

    for answer in Answer.objects.all():
        answer.response = None
        answer.save()

    Response.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_auto_20210316_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.response'),
        ),

        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.IntegerField(blank=True, choices=[(None, 'Unknown'), (0, 'Red'), (1, 'Yellow'), (2, 'Green')], null=True),
        ),

        migrations.RunPython(populate_response_field, reverse_population)
    ]
