# Generated by Django 3.1.2 on 2021-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_auto_20210316_1713'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('respondent', 'survey'), name='only_one_response_per_survey'),
        ),
    ]
