# Generated by Django 3.1.2 on 2021-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20210316_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Paragraph'), (1, 'Short answer'), (2, 'Drop-down'), (3, 'Multiple choice'), (4, 'Checkboxes'), (5, 'Slider'), (6, 'File upload')], default=0),
        ),
    ]
