# Generated by Django 3.1.2 on 2021-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_auto_20210318_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
