# Generated by Django 3.1.2 on 2021-03-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_delete_questiontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question']},
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique question position per survey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='position',
        ),
    ]
