# Generated by Django 3.1.2 on 2021-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_auto_20210318_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='Paragraph', max_length=32),
        ),
    ]
