# Generated by Django 3.1.6 on 2021-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_auto_20210318_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='PARAGRAPH', max_length=32),
        ),
    ]
