# Generated by Django 3.1.6 on 2021-03-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_auto_20210322_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='descriptive_name',
            new_name='name',
        ),
    ]
