# Generated by Django 3.1.6 on 2021-03-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('surveys', '0039_auto_20210325_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='responsible_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
