# Generated by Django 3.1.6 on 2021-03-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0040_survey_responsible_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='responsible_group',
        ),
    ]
