# Generated by Django 3.1.6 on 2021-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0042_survey_responsible_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('surveys.manage_survey', 'Has admin survey privileges')]},
        ),
    ]
