# Generated by Django 3.1.1 on 2020-10-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listingresponse',
            unique_together=set(),
        ),
    ]
