# Generated by Django 3.1.1 on 2020-10-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_response', '0002_auto_20201004_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingResponse',
        ),
    ]
