#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

fail=0

if ! pip list | grep -E 'black'; then
    echo -e 'Unable to find \033[1mBlack\033[0m, please install Black locally.'
    fail=1
fi

if ! pip list | grep -E 'flake8'; then
    echo -e 'Unable to find \033[1mFlake8\033[0m, please install Flake8 locally.'
    fail=1
fi

if (( $fail > 0 )); then
    exit 1
fi

cd frontend
npx lint-staged
