FROM node:12

# Create app directory
RUN mkdir -p /code
WORKDIR /code

# Installing dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci


# set environment variables
ARG GRAPHQL_BACKEND_URI
ENV GRAPHQL_BACKEND_URI $GRAPHQL_BACKEND_URI
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

# Copying source files
COPY . .

RUN ["npm", "run", "build"]

CMD ["npm", "run", "start"]
