# syntax=docker/dockerfile:1

FROM node:12

# Create app directory
RUN mkdir -p /code
WORKDIR /code

# Installing dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci


ENV NODE_ENV test

# Copying source files
COPY . .

# Secrets should not be passed as build args.
RUN ["npm", "run", "build"]

CMD ["npm", "run", "start"]
