# Generated by Django 3.1.6 on 2021-04-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="application",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="case",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="interview",
            field=models.BooleanField(default=False),
        ),
    ]
