# Generated by Django 3.1.6 on 2021-04-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_auto_20210412_1924"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-deadline"]},
        ),
    ]
