# Generated by Django 3.1.8 on 2021-04-18 17:26

from django.db import migrations, models
import django.db.models.deletion


def assign_default_organization(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Listing = apps.get_model("listings", "Listing")
    default_org = Organization.objects.first()
    for listing in Listing.objects.all():
        if listing.organization is None:
            listing.organization = default_org
            listing.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0021_auto_20210415_1706"),
        ("listings", "0004_auto_20210416_1534"),
    ]

    operations = [
        migrations.RunPython(assign_default_organization, lambda apps, schema_editor: None),
        migrations.AlterField(
            model_name="listing",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="listings", to="organizations.organization"
            ),
        ),
    ]
