# Generated by Django 3.1.8 on 2021-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_id'),
        ('listings', '0007_auto_20210729_0923'),
    ]

    operations = [
    ]
