# Generated by Django 3.1.8 on 2021-08-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listing_hero_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="read_more",
            field=models.URLField(blank=True, null=True),
        ),
    ]
