# Generated by Django 3.1.8 on 2021-08-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='read_more',
        ),
    ]
