# Generated by Django 3.1.8 on 2021-09-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20210902_1847'),
        ('listings', '0008_merge_20210825_1327'),
    ]

    operations = [
    ]
