# Generated by Django 3.1.1 on 2020-09-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200924_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='uuid',
            new_name='id',
        ),
    ]
