# Generated by Django 3.1.1 on 2020-09-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200924_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='id',
            new_name='temp_id',
        ),
    ]
