# Generated by Django 3.1.1 on 2020-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200927_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='new_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
