# Generated by Django 3.1.1 on 2020-09-27 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_new_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='new_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
