# Generated by Django 3.1.1 on 2020-09-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20200927_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='new_id',
            new_name='id',
        ),
    ]
