# Generated by Django 3.1.1 on 2020-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20200927_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
