# Generated by Django 3.1.1 on 2020-09-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20200927_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deadline',
            field=models.DateTimeField(default='2020-09-09T14:00+01:00'),
            preserve_default=False,
        ),
    ]
