# Generated by Django 3.1.1 on 2020-10-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('listing', '0010_listing_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
