# Generated by Django 3.1.1 on 2020-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
