# Generated by Django 3.1.1 on 2020-10-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_auto_20201008_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='listing.listing'),
        ),
    ]
