# Generated by Django 3.1.1 on 2020-10-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20201010_1028'),
        ('listing', '0014_auto_20201010_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='organizations.organization'),
        ),
    ]
