# Generated by Django 3.1.2 on 2020-10-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20201026_1632'),
        ('listing', '0014_auto_20201010_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey'),
        ),
    ]
