# Generated by Django 3.1.1 on 2020-10-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20201018_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='end_date_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='start_date_time',
            new_name='start_datetime',
        ),
    ]
