# Generated by Django 3.1.1 on 2020-10-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_listing_survey'),
        ('listing', '0016_auto_20201019_1615'),
    ]

    operations = [
    ]
