# Generated by Django 3.1.2 on 2021-01-21 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_merge_20201029_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
