# Generated by Django 3.1.2 on 2021-01-21 16:18

from django.db import migrations
import uuid

def populate_uuid_fields(apps, schema_editor):
    Response = apps.get_model("listing", "Response")
    for response in Response.objects.all():
        response.uuid = uuid.uuid4()
        response.save()


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_response_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_fields)
    ]
