# Generated by Django 3.1.2 on 2021-01-21 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_auto_20210121_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='id',
        ),
        migrations.AlterField(
            model_name='response',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
