# Generated by Django 3.1.2 on 2021-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_auto_20210121_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='uuid',
            new_name='id',
        ),
    ]
