# Generated by Django 3.1.2 on 2021-01-21 17:45

from collections import defaultdict
from django.db import migrations

def remove_duplicate_responses_from_user(apps, schema_editor):
    Responses = apps.get_model("listing", "Response")

    counter = defaultdict(list)
    for response in Responses.objects.all():
        counter[f"{response.listing_id}:{response.applicant_id}"].append(response)
    
    for key, item in counter.items():
        if len(item) > 1:
            for el in item[1:]:
                el.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20210121_1724'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_responses_from_user)
    ]
