# Generated by Django 3.1.2 on 2021-01-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0022_auto_20210121_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('applicant', 'listing'), name='unique_listing_response_for_listing'),
        ),
    ]
