# Generated by Django 3.1.2 on 2021-01-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_auto_20210121_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'permissions': [('view_responses', 'Can view all responses to a given listing')]},
        ),
    ]
