# Generated by Django 3.1.2 on 2021-03-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_auto_20210125_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
