# Generated by Django 3.1.6 on 2021-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0025_delete_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_datetime',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
