# Generated by Django 3.1.6 on 2021-04-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('listing', '0027_auto_20210322_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='survey',
        ),
        migrations.AddField(
            model_name='listing',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form'),
        ),
    ]
