# Generated by Django 3.1.6 on 2021-04-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0028_auto_20210408_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
