# pull official base image
FROM --platform=linux/amd64 python:3.9.6

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY requirements ./requirements
RUN pip install -r ./requirements/local.txt

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT celery -A celery_worker worker --concurrency=20 --loglevel=INFO