# Generated by Django 3.2.22 on 2024-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_carbooking_carbookingresponsible_carbookingsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='carbookingresponsible',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
