# Generated by Django 3.2.25 on 2024-10-17 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
