# Generated by Django 3.2.16 on 2023-02-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JanuscriptDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("Budsjett og Regnskap", "Budsjett og Regnskap"),
                            ("Generalforsamling", "Generalforsamling"),
                            ("Årbøker", "Årbøker"),
                            ("Foreningens lover", "Foreningens lover"),
                            ("Støtte fra HS", "Støtte fra HS"),
                            ("Utveksling", "Utveksling"),
                            ("Annet", "Annet"),
                            ("Januscript", "Januscript"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_location", models.CharField(default=None, max_length=2000)),
                ("featured", models.BooleanField(default=False)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("web_link", models.CharField(blank=True, default=None, max_length=2050, null=True)),
            ],
        ),
    ]
