# Generated by Django 3.2.16 on 2023-02-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("januscript", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="januscriptdocument",
            name="type_doc",
        ),
    ]
