# Generated by Django 3.2.16 on 2023-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("januscript", "0002_remove_januscriptdocument_type_doc"),
    ]

    operations = [
        migrations.AddField(
            model_name="januscriptdocument",
            name="banana",
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
