# Generated by Django 3.2.16 on 2023-02-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("januscript", "0003_januscriptdocument_banana"),
    ]

    operations = [
        migrations.RenameField(
            model_name="januscriptdocument",
            old_name="banana",
            new_name="thumbnail",
        ),
    ]
