# Generated by Django 3.2.16 on 2023-02-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("januscript", "0004_rename_banana_januscriptdocument_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="januscriptdocument",
            name="featured",
        ),
    ]
