# Generated by Django 3.2.16 on 2023-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("januscript", "0005_remove_januscriptdocument_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="januscriptdocument",
            name="thumbnail",
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
