# Generated by Django 3.1.2 on 2020-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feide_userid",
            field=models.CharField(db_index=True, default="fake-id", max_length=255),
            preserve_default=False,
        ),
    ]
