# Generated by Django 3.1.2 on 2021-03-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_id_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_token',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
