# Generated by Django 3.1.2 on 2021-03-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210308_1940"),
        ("users", "0005_auto_20210310_2022"),
    ]

    operations = []
