# Generated by Django 3.1.6 on 2021-03-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210312_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_sensitive_info', 'Can view sensitive information about a user')]},
        ),
    ]
