# Generated by Django 3.1.6 on 2021-04-15 17:03

from django.db import migrations
from django.contrib.auth import get_user_model


def populate_email_field(apps, schema_editor):
    users_without_email = get_user_model().objects.filter(email="")
    for user in users_without_email:
        setattr(user, "email", user.feide_email)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210312_1746"),
    ]

    operations = [migrations.RunPython(populate_email_field)]
