# Generated by Django 3.1.6 on 2021-04-09 09:25
from typing import TYPE_CHECKING, Type
from django.db import migrations
from guardian.models.models import UserObjectPermission
from django.contrib.auth import get_user_model

if TYPE_CHECKING:
    from django.contrib.contenttypes import models

def assign_default_permission_for_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Permission = apps.get_model("auth", "Permission")
    ContentType: Type["models.ContentType"] = apps.get_model("contenttypes", "ContentType")
    try:
        perm = Permission.objects.get(codename="view_sensitive_info")
    except Permission.DoesNotExist:
        content_type = ContentType.objects.get_for_model(User)
        perm = Permission.objects.create(
            codename="view_sensitive_info",
            name="Can view sensitive information about a user",
            content_type=content_type
        )
    for user in User.objects.all():
        UserObjectPermission.objects.create(permission=perm, user=user, object_pk=user.pk, content_type=ContentType.objects.get_for_model(user))

def remove_default_permission_for_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        perm = Permission.objects.get(codename="view_sensitive_info")
    except Permission.DoesNotExist:
        content_type = ContentType.objects.get_for_model(User)
        perm = Permission.objects.create(
            codename="view_sensitive_info",
            name="Can view sensitive information about a user",
            content_type=content_type
        )
    UserObjectPermission.objects.filter(permission=perm).delete()
    perm.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210327_1615'),
    ]

    operations = [
        migrations.RunPython(assign_default_permission_for_existing_users, remove_default_permission_for_existing_users)
    ]
