# Generated by Django 3.2.5 on 2021-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_merge_20210426_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
