# Generated by Django 3.1.8 on 2021-08-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20210426_1835'),
        ('users', '0009_alter_user_id'),
    ]

    operations = [
    ]
