# Generated by Django 3.2.5 on 2021-09-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='indok',
            field=models.BooleanField(default=False),
        ),
    ]
