# Generated by Django 3.2.5 on 2021-09-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_indok',
            field=models.BooleanField(default=False),
        ),
    ]
