# Generated by Django 3.2.5 on 2021-09-24 08:37

from typing import TYPE_CHECKING, Type
from django.db import migrations

from apps.permissions.constants import INDOK

if TYPE_CHECKING:
    from django.contrib.auth import models
    from apps.users import models as user_models


def set_current_users_to_indok(apps, schema_editor):
    Group: Type["models.Group"] = apps.get_model("auth", "Group")
    indok_group: "models.Group" = Group.objects.get(name=INDOK)
    indok_group.user_set.all().update(is_indok=True)


def set_all_users_to_not_indok(apps, schema_editor):
    User: Type["user_models.User"] = apps.get_model("users", "User")
    User.objects.all().update(is_indok=False)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20210923_1805"),
    ]

    operations = [migrations.RunPython(set_current_users_to_indok, set_all_users_to_not_indok)]
