# Generated by Django 3.2.11 on 2022-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_id_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="year_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
