# Generated by Django 3.2.11 on 2022-01-28 13:04

from django.db import migrations
from django.utils import timezone


def set_updated_year_for_recent_registraions_to_none(apps, schema_editor):
    User = apps.get_model("users", "User")
    two_days_ago = timezone.now() - timezone.timedelta(days=2)
    User.objects.filter(date_joined__gte=two_days_ago).update(year_updated_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_year_updated_at"),
    ]

    operations = []
