# Generated by Django 3.2.11 on 2022-01-27 17:19

from django.utils import timezone
from django.db import migrations


def set_last_updated_year(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.last_updated_year = timezone.now() - timezone.timedelta(days=365)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_year_updated_at"),
    ]

    operations = [migrations.RunPython(set_last_updated_year)]
