# Generated by Django 3.2.11 on 2022-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220127_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_updated_at',
            field=models.DateTimeField(),
        ),
    ]
