# Generated by Django 3.2.25 on 2026-04-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_sensitive_info", "Can view sensitive information about a user"),
                    ("manage_user_profiles", "Can search and edit other users' profiles"),
                    ("manage_user_nfc", "Can edit NFC UID/PIN for users"),
                ]
            },
        ),
    ]
