# Generated by Django 3.1.1 on 2020-09-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("title", models.CharField(max_length=128)),
                ("starttime", models.DateTimeField()),
                ("description", models.TextField()),
            ],
        ),
    ]
