# Generated by Django 3.1.1 on 2020-10-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_auto_20201005_1433"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(model_name="event", name="deadline", field=models.DateTimeField(blank=True, null=True),),
        migrations.AddField(model_name="event", name="endtime", field=models.DateTimeField(blank=True, null=True),),
        migrations.AddField(model_name="event", name="image", field=models.URLField(blank=True, default=""),),
        migrations.AddField(
            model_name="event", name="is_attendable", field=models.BooleanField(default=False), preserve_default=False,
        ),
        migrations.AddField(model_name="event", name="location", field=models.TextField(blank=True, default=""),),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="publisher",
            field=models.TextField(default="Mathilde Solberg"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="events.category"
            ),
        ),
    ]
