# Generated by Django 3.1.2 on 2021-02-04 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0008_auto_20210121_1928"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="available_slots",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="signed_up_users",
            field=models.ManyToManyField(blank=True, related_name="events", to=settings.AUTH_USER_MODEL),
        ),
    ]
