# Generated by Django 3.1.2 on 2021-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210204_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='signup_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
