# Generated by Django 3.1.2 on 2021-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_auto_20210313_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="binding_signup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
