# Generated by Django 3.1.2 on 2021-03-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_auto_20210313_1419"),
        ("events", "0011_auto_20210314_1609"),
    ]

    operations = []
