# Generated by Django 3.1.2 on 2021-03-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_allowed_grade_years'),
        ('events', '0012_merge_20210314_2142'),
    ]

    operations = [
    ]
