# Generated by Django 3.1.2 on 2021-03-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_merge_20210315_1439'),
        ('events', '0015_merge_20210315_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
