# Generated by Django 3.2.16 on 2022-10-30 15:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_auto_20210909_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="allowed_grade_years",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=[1, 2, 3, 4, 5], max_length=9
            ),
        ),
    ]
