# Generated by Django 3.2.11 on 2022-02-12 11:23

import apps.ecommerce.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210909_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_open_date', models.DateTimeField()),
                ('total_available_slots', models.PositiveIntegerField()),
                ('slot_distribution', models.JSONField(default=dict)),
                ('binding_signup', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('has_extra_information', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendable', to='events.event')),
            ],
            bases=(models.Model, apps.ecommerce.mixins.Sellable),
        ),
    ]
