# Generated by Django 3.2.5 on 2021-09-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210909_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendableEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('signup_open_date1', models.DateTimeField()),
                ('available_slots1', models.PositiveIntegerField()),
                ('available_slots_1st_year', models.PositiveIntegerField(blank=True, null=True)),
                ('available_slots_2nd_year', models.PositiveIntegerField(blank=True, null=True)),
                ('available_slots_3rd_year', models.PositiveIntegerField(blank=True, null=True)),
                ('available_slots_4th_year', models.PositiveIntegerField(blank=True, null=True)),
                ('available_slots_5th_year', models.PositiveIntegerField(blank=True, null=True)),
                ('binding_signup1', models.BooleanField(default=False)),
                ('deadline1', models.DateTimeField(blank=True, null=True)),
                ('price1', models.FloatField(blank=True, null=True)),
            ],
            bases=('events.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='Klikk her for å lese mer', max_length=100),
        ),
    ]
