# Generated by Django 3.2.5 on 2021-10-02 14:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_auto_20210909_1813"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signup_open_date", models.DateTimeField()),
                ("binding_signup", models.BooleanField(default=False)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attendable", to="events.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SlotDistribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("available_slots", models.PositiveIntegerField()),
                (
                    "grade_years",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default="1,2,3,4,5", max_length=9
                    ),
                ),
                (
                    "attendable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_distribution",
                        to="events.attendable",
                    ),
                ),
                (
                    "parent_distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_distributions",
                        to="events.slotdistribution",
                    ),
                ),
            ],
        ),
    ]
