# Generated by Django 3.2.5 on 2021-10-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_id'),
        ('events', '0018_auto_20210909_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='signup',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_up', to='ecommerce.order'),
        ),
    ]
