# Generated by Django 3.2.5 on 2021-09-30 08:40

from django.db import migrations


def move_existing_attendable_events(apps, schema_editor):
    AttendableEvent = apps.get_model("events", "AttendableEvent")
    Event = apps.get_model("events", "Event")

    existing_attendable_events = Event.objects.filter(is_attendable=True)

    for event in existing_attendable_events:
        if event.signup_open_date is None:
            setattr(event, "signup_open_date", event.start_time)
        if event.available_slots is None:
            setattr(event, "available_slots", 50)

        AttendableEvent.objects.create(
            title = event.title,
            description = event.description,
            start_time = event.start_time,
            is_attendable = event.is_attendable,
            organization = event.organization,
            publisher=event.publisher,
            end_time=event.end_time,
            location = event.location,
            category = event.category,
            image=event.image,
            has_extra_information=event.has_extra_information,
            short_description=event.short_description,  
            contact_email=event.contact_email,
            allowed_grade_years=event.allowed_grade_years,
            signup_open_date1=event.signup_open_date,
            available_slots1=event.available_slots, 
            deadline1=event.deadline, 
            price1=event.price, 
            binding_signup1=event.binding_signup
            )

    existing_attendable_events.delete() # Kan evt droppe denne linjen



class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210930_1039'),
    ]

    operations = [
        migrations.RunPython(move_existing_attendable_events)
    ]
