# Generated by Django 3.2.25 on 2026-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_allowed_grade_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
