# Generated by Django 3.2.11 on 2022-02-12 11:26

from django.db import migrations


def restructure_existing_attendable_events(apps, schema_editor):
    attendable_model = apps.get_model("events", "Attendable")
    event_model = apps.get_model("events", "Event")

    existing_attendable_events = event_model.objects.filter(is_attendable=True)

    for event in existing_attendable_events:
        if event.signup_open_date is None:
            setattr(event, "signup_open_date", event.start_time)
        if event.available_slots is None:
            setattr(event, "available_slots", 0)

        allowed_grade_years_string = ""
        for grade_year in event.allowed_grade_years:
            allowed_grade_years_string += grade_year + ","

        slot_distribution = {allowed_grade_years_string[:-1]: event.available_slots}

        attendable_model.objects.create(
            event=event,
            signup_open_date=event.signup_open_date,
            deadline=event.deadline,
            price=event.price,
            binding_signup=event.binding_signup,
            total_available_slots=event.available_slots,
            slot_distribution=slot_distribution,
            has_extra_information=event.has_extra_information,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_attendable"),
    ]

    operations = [migrations.RunPython(restructure_existing_attendable_events, migrations.RunPython.noop)]
