# Generated by Django 3.2.25 on 2024-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_event_allowed_grade_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='grade1_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='grade2_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='grade3_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='grade4_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='grade5_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
