# Generated by Django 3.2.25 on 2024-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20240930_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='grade1_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade2_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade3_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade4_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade5_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0]),
        ),
    ]
