# Generated by Django 3.2.22 on 2024-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20240930_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.JSONField(default=list),
        ),
    ]
