# Generated by Django 3.2.5 on 2021-09-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_move_existing_attendable_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='event',
            name='binding_signup',
        ),
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='has_extra_information',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_attendable',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='signup_open_date',
        ),
    ]
