# Generated by Django 3.2.25 on 2024-10-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20241007_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.JSONField(default=list),
        ),
    ]
