# Generated by Django 3.2.5 on 2021-09-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20210930_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendableevent',
            old_name='available_slots1',
            new_name='available_slots',
        ),
        migrations.RenameField(
            model_name='attendableevent',
            old_name='binding_signup1',
            new_name='binding_signup',
        ),
        migrations.RenameField(
            model_name='attendableevent',
            old_name='deadline1',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='attendableevent',
            old_name='price1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='attendableevent',
            old_name='signup_open_date1',
            new_name='signup_open_date',
        ),
    ]
