# Generated by Django 3.2.25 on 2024-10-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tickets',
            new_name='year_slots',
        ),
    ]
