# Generated by Django 3.2.12 on 2022-02-21 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0022_auto_20220221_1735"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="signup",
            unique_together={("user_id", "event_id")},
        ),
    ]
