# Generated by Django 3.2.12 on 2022-03-14 16:46

from django.db import migrations


def restructure_product_events(apps, schema_editor):
    event_model = apps.get_model("events", "Event")
    product_model = apps.get_model("ecommerce", "Product")
    attendable_model = apps.get_model("events", "Attendable")
    content_type_model = apps.get_model("contenttypes", "ContentType")

    existing_event_products = product_model.objects.filter(
        content_type=content_type_model.objects.get_for_model(event_model)
    )

    for product in existing_event_products:
        event = event_model.objects.get(id=product.object_id)
        setattr(product, "object_id", event.attendable.id)
        setattr(
            product,
            "content_type",
            content_type_model.objects.get_for_model(attendable_model),
        )
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_alter_signup_unique_together"),
    ]

    operations = [migrations.RunPython(restructure_product_events, migrations.RunPython.noop)]
