# Generated by Django 3.2.25 on 2024-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_rename_tickets_event_year_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='year_slots',
            new_name='slots_per_year',
        ),
    ]
