# Generated by Django 3.2.25 on 2024-10-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_tickets'),
        ('events', '0024_rename_year_slots_event_slots_per_year'),
    ]

    operations = [
    ]
