# Generated by Django 3.2.25 on 2024-11-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_merge_20241028_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='grade1_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade2_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade3_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade4_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='grade5_tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
    ]
