# Generated by Django 3.2.25 on 2025-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20241104_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_year_divided',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
