# Generated by Django 3.2.25 on 2025-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_event_is_year_divided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_year_divided',
            field=models.BooleanField(default=False),
        ),
    ]
