mutation CreateJanhusBooking($bookingData: JanHusBookingInput!) {
  createJanhusBooking(bookingData: $bookingData) {
    ok
    booking {
      ...JanHusBooking
    }
  }
}

mutation UpdateJanhusBooking($bookingData: UpdateJanHusBookingInput!) {
  updateJanhusBooking(bookingData: $bookingData) {
    ok
    booking {
      ...JanHusBooking
    }
    overlappingBookings {
      id
      reference
      startsAt
      endsAt
      area {
        id
        name
      }
    }
  }
}

mutation ReviewJanhusBooking($reviewData: ReviewJanHusBookingInput!) {
  reviewJanhusBooking(reviewData: $reviewData) {
    ok
    booking {
      ...JanHusBooking
    }
  }
}

mutation CreateJanhusBookingRequest($requestData: JanHusBookingRequestInput!) {
  createJanhusBookingRequest(requestData: $requestData) {
    ok
    bookingRequest {
      ...JanHusBookingRequest
    }
  }
}

mutation ReviewJanhusBookingRequest($reviewData: ReviewJanHusBookingRequestInput!) {
  reviewJanhusBookingRequest(reviewData: $reviewData) {
    ok
    bookingRequest {
      ...JanHusBookingRequest
    }
    booking {
      ...JanHusBooking
    }
    overlappingBookings {
      id
      reference
      startsAt
      endsAt
      area {
        id
        name
      }
    }
  }
}

mutation UpdateJanhusBookingSettings($settingsData: JanHusBookingSettingsInput!) {
  updateJanhusBookingSettings(settingsData: $settingsData) {
    ok
    bookingSettings {
      ...JanHusBookingSettings
    }
  }
}

mutation CreateJanhusArea($areaData: JanHusAreaInput!) {
  createJanhusArea(areaData: $areaData) {
    ok
    area {
      ...JanHusArea
    }
  }
}

mutation UpdateJanhusArea($areaData: UpdateJanHusAreaInput!) {
  updateJanhusArea(areaData: $areaData) {
    ok
    area {
      ...JanHusArea
    }
  }
}

mutation DeleteJanhusArea($id: ID!) {
  deleteJanhusArea(id: $id) {
    ok
  }
}

mutation CreateJanhusPaymentProduct($bookingId: ID!) {
  createJanhusPaymentProduct(bookingId: $bookingId) {
    ok
    productId
    booking {
      ...JanHusBooking
    }
  }
}

mutation DeleteJanhusBooking($bookingId: ID!) {
  deleteJanhusBooking(bookingId: $bookingId) {
    ok
  }
}

mutation DeleteJanhusBookingRequest($requestId: ID!) {
  deleteJanhusBookingRequest(requestId: $requestId) {
    ok
  }
}
