query JanHusBookings($startsAt: DateTime, $endsAt: DateTime, $area: ID) {
  janhusBookings(startsAt: $startsAt, endsAt: $endsAt, area: $area) {
    ...JanHusBookingAvailability
  }
}

query JanHusMyBookings {
  janhusMyBookings {
    ...JanHusBooking
  }
}

query JanHusMyBookingRequests {
  janhusMyBookingRequests {
    ...JanHusBookingRequest
  }
}

query JanHusGuestSearch($bookingId: ID!, $query: String!, $limit: Int) {
  janhusGuestSearch(bookingId: $bookingId, query: $query, limit: $limit) {
    ...JanHusGuestListEntry
  }
}

query JanHusGuestSearchForRequest($query: String!, $limit: Int) {
  janhusGuestSearchForRequest(query: $query, limit: $limit) {
    ...JanHusGuestListEntry
  }
}

query AdminJanHusBookings($status: String) {
  adminJanhusBookings(status: $status) {
    ...JanHusBooking
  }
}

query JanHusBookableOrganizations {
  janhusBookableOrganizations {
    id
    name
  }
}

query JanHusBookingSettings {
  janhusBookingSettings {
    ...JanHusBookingSettings
  }
}

query JanHusAreas($includeInactive: Boolean) {
  janhusAreas(includeInactive: $includeInactive) {
    ...JanHusArea
  }
}

query JanHusBookingLevels {
  janhusBookingLevels {
    ...JanHusBookingLevel
  }
}

query JanHusMyBookingLevel {
  janhusMyBookingLevel {
    ...JanHusBookingLevel
  }
}

query JanHusBookingRequests($status: String) {
  janhusBookingRequests(status: $status) {
    ...JanHusBookingRequest
  }
}
