# Generated by Django 3.1.6 on 2021-04-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210408_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'permissions': [('forms.manage_form', 'Has admin form privileges')]},
        ),
    ]
