# Generated by Django 3.1.8 on 2021-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
