# Generated by Django 3.1.8 on 2021-05-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_answer_user'),
        ('forms', '0003_auto_20210408_1842'),
    ]

    operations = [
    ]
