# Generated by Django 3.1.8 on 2021-05-03 16:10

from django.db import migrations

def populate_position(apps, schema_editor):
    Form = apps.get_model("forms", "Form")

    for form in Form.objects.all():
        for index, question in enumerate(form.questions):
            question.position = index
            question.save(update_fields=["position"])

class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_add_position'),
    ]

    operations = [
        migrations.RunPython(populate_position)
    ]
