# Generated by Django 3.1.8 on 2021-05-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_merge_20210501_1156"),
        ("forms", "0004_auto_20210501_1201"),
    ]

    operations = []
