# Generated by Django 3.2.5 on 2021-07-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210721_1917'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_answer_to_question_per_user',
        ),
    ]
