# Generated by Django 3.2.5 on 2021-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_answer_unique_answer_to_question_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_to_question_per_user'),
        ),
    ]
