# Generated by Django 3.1.8 on 2021-07-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_merge_20210526_1851"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"permissions": [("manage_form", "Has admin form privileges")]},
        ),
    ]
