# Generated by Django 3.1.8 on 2021-08-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210729_1247'),
        ('forms', '0006_answer_unique_answer_to_question_per_user'),
    ]

    operations = [
    ]
