# Generated by Django 3.1.8 on 2021-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210729_1247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_answer_to_question_per_user',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_response'),
        ),
    ]
