# Generated by Django 3.1.8 on 2021-09-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20210902_2002'),
        ('forms', '0004_auto_20210721_1917'),
    ]

    operations = [
    ]
