# Generated by Django 3.1.8 on 2021-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiblegroup",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="responsiblegroup",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
