# Generated by Django 3.1.8 on 2021-08-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0031_auto_20210824_1446"),
        ("permissions", "0003_auto_20210824_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiblegroup",
            name="group_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="responsiblegroup",
            name="temp_organization",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
            ),
        ),
    ]
