# Generated by Django 3.1.8 on 2021-08-24 12:46

from typing import TYPE_CHECKING, Type
from django.db import migrations

from apps.permissions.constants import ADMIN_GROUP_TYPE, MEMBER_GROUP_TYPE

if TYPE_CHECKING:
    from apps.organizations import models as org_models
    from apps.permissions import models as perm_models


def move_permission_groups_to_fk(apps, _):
    ResponsibleGroup: Type["perm_models.ResponsibleGroup"] = apps.get_model("permissions", "ResponsibleGroup")
    Organization: Type["org_models.Organization"] = apps.get_model("organizations", "Organization")

    for organization in Organization.objects.all():
        member_group = organization.member_group
        admin_group = organization.admin_group

        if member_group and admin_group:
            member_group.group_type = MEMBER_GROUP_TYPE
            admin_group.group_type = ADMIN_GROUP_TYPE

            # Name as of this migration
            member_group.temp_organization = organization
            admin_group.temp_organization = organization

            member_group.save()
            admin_group.save()

            organization.member_group = None
            organization.admin_group = None
            organization.save()

    # Delete orphan responsible groups
    ResponsibleGroup.objects.filter(temp_organization=None).delete()


def move_permission_groups_to_one_to_one_field(apps, _):
    Organization: Type["org_models.Organization"] = apps.get_model("organizations", "Organization")
    ResponsibleGroup: Type["perm_models.ResponsibleGroup"] = apps.get_model("permissions", "ResponsibleGroup")

    organization: "org_models.Organization"
    for organization in Organization.objects.all():
        organization.member_group = ResponsibleGroup.objects.get(
            temp_organization=organization, group_type=MEMBER_GROUP_TYPE
        )
        organization.admin_group = ResponsibleGroup.objects.get(
            temp_organization=organization, group_type=ADMIN_GROUP_TYPE
        )
        organization.save()


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_auto_20210824_1446"),
    ]

    operations = [migrations.RunPython(move_permission_groups_to_fk, move_permission_groups_to_one_to_one_field)]
