# Generated by Django 3.1.8 on 2021-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_auto_20210824_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsiblegroup',
            name='group_type',
            field=models.CharField(max_length=50),
        ),
    ]
