# Generated by Django 3.1.8 on 2021-08-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0006_auto_20210824_1457"),
    ]

    operations = [
        migrations.RenameField(
            model_name="responsiblegroup",
            old_name="temp_organization",
            new_name="organization",
        ),
    ]
