# Generated by Django 3.1.8 on 2021-08-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_auto_20210824_1457"),
        ("permissions", "0007_auto_20210824_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblegroup",
            name="organization",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
        ),
    ]
