# Generated by Django 3.2.5 on 2021-09-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_auto_20210824_2126"),
        ("permissions", "0010_auto_20210824_1546"),
    ]

    operations = []
