# Generated by Django 3.2.16 on 2022-11-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0011_merge_0004_auto_20210824_2126_0010_auto_20210824_1546"),
        ("permissions", "0034_auto_20221114_1854"),
    ]

    operations = []
