# Generated by Django 3.2.25 on 2026-04-29 13:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0005_rename_delivered_order_delivered_product'),
        ('organizations', '0034_alter_organization_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JanHusAreaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('FIRST_FLOOR', '1st floor'), ('SECOND_FLOOR', '2nd floor'), ('ENTIRE_HOUSE', 'Entire house')], max_length=32, unique=True)),
                ('internal_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('external_price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='JanHusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('area', models.CharField(choices=[('FIRST_FLOOR', '1st floor'), ('SECOND_FLOOR', '2nd floor'), ('ENTIRE_HOUSE', 'Entire house')], max_length=32)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('PENDING_ADMIN_REVIEW', 'Pending admin review'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('BLOCKED', 'Blocked')], default='PENDING_ADMIN_REVIEW', max_length=32)),
                ('is_external_booking', models.BooleanField(default=False)),
                ('booker_name', models.CharField(blank=True, default='', max_length=200)),
                ('booker_email', models.EmailField(blank=True, default='', max_length=254)),
                ('booker_phone', models.CharField(blank=True, default='', max_length=32)),
                ('responsible_name', models.CharField(max_length=200)),
                ('responsible_email', models.EmailField(max_length=254)),
                ('responsible_phone', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('OPEN_FOR_INDOK', 'Open to all Indøk students'), ('PRIVATE', 'Private'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=32)),
                ('cleaning_requested', models.BooleanField(default=False)),
                ('deposit_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('REQUIRED', 'Required'), ('REQUESTED', 'Requested'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('WITHHELD', 'Withheld')], default='REQUIRED', max_length=32)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('bankid_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('SIGNED', 'Signed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=32)),
                ('bankid_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at'],
                'permissions': [('manage_booking', 'Can manage JanHus bookings'), ('manage_settings', 'Can manage JanHus booking settings'), ('review_booking', 'Can review JanHus bookings')],
            },
        ),
        migrations.CreateModel(
            name='JanHusBookingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('can_book_anytime', models.BooleanField(default=False)),
                ('can_create_provisional', models.BooleanField(default=False)),
                ('can_create_confirmed', models.BooleanField(default=True)),
                ('can_override_lower_levels', models.BooleanField(default=False)),
                ('can_edit_own_bookings_only', models.BooleanField(default=True)),
                ('can_edit_all_bookings', models.BooleanField(default=False)),
                ('booking_opens_weeks_before', models.PositiveIntegerField(blank=True, help_text='If empty, the level can create bookings all year according to its flags.', null=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JanHusBookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_duration_minutes', models.PositiveIntegerField(default=60)),
                ('slot_granularity_minutes', models.PositiveIntegerField(default=30)),
                ('opening_hour', models.PositiveIntegerField(default=8)),
                ('closing_hour', models.PositiveIntegerField(default=2)),
                ('buffer_minutes', models.PositiveIntegerField(default=0)),
                ('organization_booking_opens_weeks_before', models.PositiveIntegerField(default=6)),
                ('general_booking_opens_weeks_before', models.PositiveIntegerField(default=4)),
                ('bankid_provider', models.CharField(default='IDURA_STUB', max_length=100)),
            ],
            options={
                'verbose_name': 'JanHus booking settings',
                'verbose_name_plural': 'JanHus booking settings',
            },
        ),
        migrations.CreateModel(
            name='JanHusUserBookingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='janhus.janhusbookinglevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janhus_booking_level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JanHus user booking level',
                'verbose_name_plural': 'JanHus user booking levels',
            },
        ),
        migrations.CreateModel(
            name='JanHusOrganizationBookingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='janhus.janhusbookinglevel')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janhus_booking_level', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'JanHus organization booking level',
                'verbose_name_plural': 'JanHus organization booking levels',
            },
        ),
        migrations.CreateModel(
            name='JanHusBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('area', models.CharField(choices=[('FIRST_FLOOR', '1st floor'), ('SECOND_FLOOR', '2nd floor'), ('ENTIRE_HOUSE', 'Entire house')], max_length=32)),
                ('requester_name', models.CharField(blank=True, default='', max_length=200)),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requester_phone', models.CharField(blank=True, default='', max_length=32)),
                ('responsible_name', models.CharField(max_length=200)),
                ('responsible_email', models.EmailField(max_length=254)),
                ('responsible_phone', models.CharField(max_length=32)),
                ('event_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('OPEN_FOR_INDOK', 'Open to all Indøk students'), ('PRIVATE', 'Private'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=32)),
                ('cleaning_requested', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='janhus.janhusbooking')),
                ('owner_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_booking_requests', to='organizations.organization')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='booking_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='janhus.janhusbookinglevel'),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_created_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_bookings', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_owned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='vipps_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_bookings', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='vipps_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='janhus_bookings', to='ecommerce.product'),
        ),
    ]
