# Generated by Django 3.2.25 on 2026-08-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0007_add_booking_semesters_to_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janhusareaconfiguration',
            options={'ordering': ['area'], 'verbose_name': 'JanHus area configuration', 'verbose_name_plural': 'JanHus area configurations'},
        ),
        migrations.AlterModelOptions(
            name='janhusbooking',
            options={'ordering': ['starts_at'], 'permissions': [('manage_booking', 'Can manage JanHus bookings'), ('manage_settings', 'Can manage JanHus booking settings'), ('review_booking', 'Can review JanHus bookings')], 'verbose_name': 'JanHus booking', 'verbose_name_plural': 'JanHus bookings'},
        ),
        migrations.AlterModelOptions(
            name='janhusbookinglevel',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'JanHus booking level', 'verbose_name_plural': 'JanHus booking levels'},
        ),
        migrations.AlterModelOptions(
            name='janhusbookingrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'JanHus booking request', 'verbose_name_plural': 'JanHus booking requests'},
        ),
    ]
