# Generated by Django 3.2.25 on 2026-08-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0008_auto_20260825_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='private_bookings_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
