# Generated by Django 3.2.25 on 2026-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0009_janhusbookingsettings_private_bookings_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbooking',
            name='manually_marked_as_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='price_override_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='janhusbooking',
            name='price_override_tier',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], max_length=16, null=True),
        ),
    ]
