# Generated by Django 3.2.25 on 2026-08-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0011_convert_area_to_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='cleaning_option_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
