# Generated by Django 3.2.25 on 2026-08-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_alter_organization_options'),
        ('janhus', '0012_janhusbookingsettings_cleaning_option_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='payment_provider_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='janhus_payment_settings', to='organizations.organization'),
        ),
    ]
