# Generated by Django 3.2.25 on 2026-08-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0014_janhusbooking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='booking_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
