# Generated by Django 3.2.25 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janhus', '0015_janhusbookingsettings_booking_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='booking_contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='janhusbookingsettings',
            name='booking_contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
