# Generated by Django 3.2.5 on 2021-10-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="blogpost", old_name="publishDate", new_name="publish_date",),
    ]
