# Generated by Django 3.2.5 on 2021-10-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blog",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="blog_post", to="blogs.blog"
            ),
        ),
    ]
