# Generated by Django 3.2.5 on 2021-10-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_auto_20211025_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="blog_post", to="blogs.blog"
            ),
        ),
    ]
