# Generated by Django 3.2.5 on 2021-11-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_alter_blogpost_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="blog_posts", to="blogs.blog"
            ),
        ),
    ]
