# Generated by Django 3.2.22 on 2024-02-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_alter_organization_options'),
        ('blogs', '0007_alter_blogpost_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog', to='organizations.organization'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
