query nfcCards {
	nfcCards {
		...NfcCard
	}
}

query nfcCard($mifareCsn: String!) {
	nfcCard(mifareCsn: $mifareCsn) {
		...NfcCard
	}
}

query nfcCardAssignments($activeOnly: Boolean) {
	nfcCardAssignments(activeOnly: $activeOnly) {
		...NfcCardAssignment
	}
}

query myNfcCardAssignment {
	myNfcCardAssignment {
		...NfcCardAssignment
	}
}

query nfcAccessGrants($activeOnly: Boolean) {
	nfcAccessGrants(activeOnly: $activeOnly) {
		...NfcAccessGrant
	}
}

query nfcAccessEvents($limit: Int, $doorIdentifier: String) {
	nfcAccessEvents(limit: $limit, doorIdentifier: $doorIdentifier) {
		...NfcAccessEvent
	}
}
