# Generated by Django 3.1.6 on 2021-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="auth_token",
            field=models.CharField(default="1e8c58f45c3940dc98e9ac01aebf2e66", max_length=32),
        ),
    ]
