# Generated by Django 3.1.6 on 2021-04-02 17:28

import apps.ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_order_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="auth_token",
            field=models.CharField(default=apps.ecommerce.models.get_auth_token, max_length=32),
        ),
    ]
