# Generated by Django 3.2.22 on 2024-02-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20231113_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_item',
            field=models.BooleanField(default=False),
        ),
    ]
