# Generated by Django 3.1.6 on 2021-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_vippsaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('INITIATED', 'initiated'), ('RESERVED', 'reserved'), ('CAPTURED', 'captured'), ('CANCELLED', 'cancelled'), ('REFUNDED', 'refunded')], default='INITIATED', max_length=255),
        ),
    ]
