# Generated by Django 3.2.22 on 2024-02-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_order_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_product',
        ),
    ]
