# Generated by Django 3.2.25 on 2026-09-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_delivered_order_delivered_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_attempt', models.PositiveIntegerField()),
                ('refunded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='ecommerce.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderpaymentattempt',
            constraint=models.UniqueConstraint(fields=('order', 'payment_attempt'), name='unique_order_payment_attempt'),
        ),
    ]
