# Generated by Django 3.1.6 on 2021-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210405_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('INITIATED', 'initiated'), ('RESERVED', 'reserved'), ('CAPTURED', 'captured'), ('CANCELLED', 'cancelled'), ('REFUNDED', 'refunded'), ('FAILED', 'failed'), ('REJECTED', 'rejected')], default='INITIATED', max_length=255),
        ),
    ]
