# Generated by Django 3.1.6 on 2021-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20210406_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempt',
            field=models.IntegerField(default=1),
        ),
    ]
