# Generated by Django 3.2.5 on 2021-10-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_buyable_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
