# Generated by Django 3.2.5 on 2022-01-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecommerce", "0009_auto_20211018_1840"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
