# Generated by Django 3.2.10 on 2022-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0011_auto_20220117_1858"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_attempt",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="current_quantity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="max_buyable_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="total_quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
