# Generated by Django 3.2.10 on 2022-01-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecommerce", "0012_auto_20220118_1156"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("content_type", "object_id")},
        ),
    ]
