# Generated by Django 3.1.1 on 2020-10-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(null=True, upload_to="organizations"),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"
            ),
        ),
    ]
