# Generated by Django 3.1.1 on 2020-10-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20201001_1605"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="organizations"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="organizations.organization",
            ),
        ),
    ]
