# Generated by Django 3.1.1 on 2020-10-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20201005_1639'),
        ('organizations', '0004_auto_20201005_1433'),
    ]

    operations = [
    ]
