# Generated by Django 3.1.1 on 2020-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_auto_20201005_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=100),
        ),
    ]
