# Generated by Django 3.1.2 on 2021-01-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_merge_20201005_1654'),
        ('organizations', '0005_auto_20201010_1028'),
    ]

    operations = [
    ]
