# Generated by Django 3.1.2 on 2020-11-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organization_color"),
        ("organizations", "0005_merge_20201005_1654"),
    ]

    operations = []
