# Generated by Django 3.1.2 on 2021-01-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_merge_20210117_1655'),
        ('organizations', '0007_merge_20201102_1637'),
    ]

    operations = [
    ]
