# Generated by Django 3.1.2 on 2021-02-04 16:18
from collections import defaultdict
from django.db import migrations
from uuid import uuid4


def non_destructively_uniquify_organizations_and_parents(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    for organization in Organization.objects.all():
        occupied_names = dict()
        for child in organization.children.all():
            occupied_names[child.name] = occupied_names.get(child.name, 0) + 1
            if occupied_names[child.name] > 1:
                child.name = child.name + str(uuid4())[:8]
                child.save()


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_auto_20210201_1720"),
    ]

    operations = [
        migrations.RunPython(non_destructively_uniquify_organizations_and_parents),
    ]
