# Generated by Django 3.1.2 on 2021-02-08 16:55

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.models import RenameModel
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0011_auto_20210204_1735"),
    ]

    operations = [
        migrations.RenameField("Member", "member", "user"),
        migrations.RenameModel("Member", "Membership"),
    ]
