# Generated by Django 3.1.2 on 2021-03-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_auto_20210308_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="organizations.organization",
            ),
        ),
    ]
