# Generated by Django 3.1.2 on 2021-03-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20210314_2249'),
        ('organizations', '0017_auto_20210314_2148'),
    ]

    operations = [
    ]
