# Generated by Django 3.1.2 on 2021-03-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_auto_20210315_1429'),
        ('organizations', '0019_merge_20210315_1439'),
    ]

    operations = [
    ]
