# Generated by Django 3.1.6 on 2021-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_organization_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
