# Generated by Django 3.1.8 on 2021-04-22 18:13

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20210415_1706'),
        ('organizations', '0020_auto_20210409_1629'),
    ]

    operations = [
    ]
