# Generated by Django 3.1.8 on 2021-04-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_merge_20210422_2013'),
    ]

    operations = [
    ]
