# Generated by Django 3.1.8 on 2021-04-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0002_auto_20210422_2020"),
        ("organizations", "0026_auto_20210426_1802"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="role",
        ),
        migrations.AddField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="permissions.responsiblegroup",
            ),
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
