# Generated by Django 3.1.8 on 2021-04-26 17:48

from django.db import migrations

def add_existing_members_to_primary_group(apps, schema_editor):
    Membership = apps.get_model("organizations", "Membership")

    for membership in Membership.objects.all():
        group = membership.organization.primary_group.group
        user = membership.user
        user.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_auto_20210426_1843'),
    ]

    operations = [
        migrations.RunPython(add_existing_members_to_primary_group, lambda apps, schema_editor: None)
    ]
