# Generated by Django 3.1.8 on 2021-08-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20210824_1213'),
        ('organizations', '0030_auto_20210426_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='hr_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_organization', to='permissions.responsiblegroup'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization', to='permissions.responsiblegroup'),
        ),
    ]
