# Generated by Django 3.1.8 on 2021-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_auto_20210426_2129'),
        ('organizations', '0022_auto_20210721_1914'),
    ]

    operations = [
    ]
