# Generated by Django 3.2.5 on 2021-09-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20210909_1813'),
        ('organizations', '0032_auto_20210824_1457'),
    ]

    operations = [
    ]
