# Generated by Django 3.2.16 on 2022-10-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0034_migrate_org_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"permissions": [("manage_organization", "Can manage organizations, used for admins")]},
        ),
    ]
