# Generated by Django 3.2.5 on 2021-10-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0037_alter_membership_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("add_listing", "Add listing to organization"),
                    ("add_form", "Add form to organization"),
                    ("add_event", "Add event by organization"),
                )
            },
        ),
    ]
