# Generated by Django 3.1.1 on 2020-10-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_auto_20200928_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
