# Generated by Django 3.1.2 on 2021-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0004_auto_20201102_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cabins',
            field=models.ManyToManyField(to='cabins.Cabin'),
        ),
    ]
