# Generated by Django 3.1.2 on 2021-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0005_booking_cabins"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="external_price",
            field=models.IntegerField(default=2700),
        ),
        migrations.AddField(
            model_name="cabin",
            name="internal_price",
            field=models.IntegerField(default=1100),
        ),
        migrations.AddField(
            model_name="cabin",
            name="max_guests",
            field=models.IntegerField(default=20),
        ),
    ]
