# Generated by Django 3.1.2 on 2021-03-22 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0006_auto_20210322_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 20, 10, 8, 577923)),
            preserve_default=False,
        ),
    ]
