# Generated by Django 3.1.6 on 2021-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0009_auto_20210327_1240"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(max_length=8),
        ),
    ]
