# Generated by Django 3.1.6 on 2021-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0011_auto_20210412_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_tentative',
            field=models.BooleanField(default=False),
        ),
    ]
