# Generated by Django 3.1.6 on 2021-04-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0011_auto_20210412_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='surname',
            new_name='lastname',
        ),
    ]
