# Generated by Django 3.1.6 on 2021-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0012_auto_20210416_0914"),
        ("cabins", "0012_booking_is_tentative"),
    ]

    operations = []
