# Generated by Django 3.1.6 on 2021-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0013_merge_20210419_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_tentative',
            field=models.BooleanField(default=True),
        ),
    ]
