# Generated by Django 3.2.5 on 2021-10-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0006_auto_20210909_1813"),
        ("cabins", "0016_auto_20210929_2028"),
    ]

    operations = []
