# Generated by Django 3.2.5 on 2021-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0017_merge_0006_auto_20210909_1813_0016_auto_20210929_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bookingresponsible",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
