# Generated by Django 3.2.5 on 2021-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0019_bookingsemester"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsemester",
            name="fall_semester_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookingsemester",
            name="spring_semester_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
