# Generated by Django 3.2.11 on 2022-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0018_auto_20211007_1740"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
