# Generated by Django 3.2.11 on 2022-02-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0019_alter_booking_options"),
        ("cabins", "0020_auto_20211111_1825"),
    ]

    operations = []
