# Generated by Django 3.2.11 on 2022-02-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabins", "0020_auto_20211111_1825"),
        ("cabins", "0021_booking_is_declined"),
    ]

    operations = []
