# Generated by Django 3.2.12 on 2022-02-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0021_merge_20220217_1947'),
        ('cabins', '0022_merge_20220210_1705'),
    ]

    operations = [
    ]
