# Generated by Django 3.2.12 on 2022-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0023_merge_20220228_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='extra_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
