# Generated by Django 3.2.22 on 2023-11-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabins", "0027_auto_20220425_1811"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabin",
            name="external_price_weekend",
            field=models.PositiveIntegerField(default=5400),
        ),
        migrations.AddField(
            model_name="cabin",
            name="internal_price_weekend",
            field=models.PositiveIntegerField(default=1100),
        ),
        migrations.AlterField(
            model_name="cabin",
            name="external_price",
            field=models.PositiveIntegerField(default=3950),
        ),
    ]
