# Generated by Django 3.2.22 on 2024-02-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cabins", "0028_auto_20231113_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="bookingresponsible",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
