# Generated by Django 3.2.22 on 2024-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0029_auto_20240226_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='external_student_price',
            field=models.PositiveIntegerField(default=2950),
        ),
        migrations.AddField(
            model_name='cabin',
            name='external_student_price_weekend',
            field=models.PositiveIntegerField(default=3950),
        ),
    ]
